[package]
name = "sac-jni"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
sac = { path = "../sac" }
jni = "0.21.1"

[lib]
name = "sac_jni"
crate_type = ["cdylib"]